# Generated by Django 5.1.2 on 2024-10-24 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=2)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Atividade', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='receita',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('tempo', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='utensilio',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='valores_nutricionais',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('gordura', models.DecimalField(decimal_places=2, max_digits=2)),
                ('carboidrato', models.DecimalField(decimal_places=2, max_digits=2)),
                ('proteina', models.DecimalField(decimal_places=2, max_digits=2)),
                ('porção', models.DecimalField(decimal_places=2, max_digits=2)),
                ('unidade', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='favoritado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlavourIt_app.client')),
                ('id_Receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlavourIt_app.receita')),
            ],
        ),
        migrations.CreateModel(
            name='receita_utensilio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlavourIt_app.receita')),
                ('id_utensilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlavourIt_app.utensilio')),
            ],
        ),
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quant', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('unidade', models.TextField()),
                ('id_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlavourIt_app.receita')),
                ('id_val_Nutri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlavourIt_app.valores_nutricionais')),
            ],
        ),
    ]
