# Generated by Django 4.2.16 on 2024-10-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourIt_app', '0002_alter_valores_nutricionais_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utensilio',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
