# Generated by Django 5.1.3 on 2024-11-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourIt_app', '0003_alter_utensilio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Birth_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
