# Generated by Django 4.2.16 on 2024-11-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourIt_app', '0004_client_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
