# Generated by Django 4.2.16 on 2024-11-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourIt_app', '0005_alter_ingredient_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='valores_nutricionais',
            name='carboidrato',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='valores_nutricionais',
            name='gordura',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='valores_nutricionais',
            name='porção',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='valores_nutricionais',
            name='proteina',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
