# Generated by Django 5.1.3 on 2024-11-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourIt_app', '0006_alter_client_altura_alter_client_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.TextField(default='username'),
        ),
    ]
