# Generated by Django 5.1.3 on 2024-12-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourIt_app', '0007_client_email_client_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pwd',
            field=models.TextField(default='password'),
        ),
    ]
