# Generated by Django 5.1.3 on 2024-12-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourIt_app', '0008_client_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
