# Generated by Django 5.1.3 on 2024-12-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourIt_app', '0009_alter_client_altura_alter_client_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
    ]
