# Generated by Django 4.2.16 on 2024-12-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourIt_app', '0010_remove_client_email_remove_client_pwd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='receita_usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('tempo', models.TextField()),
                ('instructions', models.TextField()),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlavourIt_app.client')),
            ],
        ),
    ]
