# Generated by Django 4.2.16 on 2024-12-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourIt_app', '0011_receita_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita_usuario',
            name='id_Cliente',
        ),
        migrations.AddField(
            model_name='receita',
            name='id_Cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FlavourIt_app.client'),
        ),
    ]
